### ISSUE TITLE
Doesn't seem to work with artifactory 4.7.4 and jspm 0.16.29

### ISSUE THREAD

**Issue by jabbera** [jtamary/jspm-artifactory-github#1]
Hi. This looks like exactly what we need to download github packages from JSPM. However all packages are returning a 404 when I do a jspm install after configuring the plugin. I followed your directions to the letter (I think) and no packages can be resolved. Here is the artifactory log file. Any idea?

```
'null' Cached key has been found for request: '/artifactory/api/vcs/github/artifactory/api/vcs/tags/github-remote/twbs/bootstrap' with method: 'GET'
Entering request GET (127.0.0.1) /api/vcs/github/artifactory/api/vcs/tags/github-remote/twbs/bootstrap.
Could not transform artifactory/api/vcs/tags/github-remote/twbs/bootstrap to a valid module info.
Could not transform artifactory/api/vcs/tags/github-remote/twbs/bootstrap to a valid module info.
Could not transform artifactory/api/vcs/tags/github-remote/twbs/bootstrap to a valid module info.
github is not a valid module info -  'artifactory/api/vcs/tags/github-remote/twbs/bootstrap': not enforcing snapshot/release policy.
Could not transform artifactory/api/vcs/tags/github-remote/twbs/bootstrap to a valid module info.
Could not transform artifactory/api/vcs/tags/github-remote/twbs/bootstrap to a valid module info.
github-cache is not a valid module info -  'artifactory/api/vcs/tags/github-remote/twbs/bootstrap': not enforcing 
Check isNewerThan. resourceLastModified=0, roundedResourceLastModified=0, modificationTime=0
Sending HTTP error code 404: Not Found
Exiting request GET (127.0.0.1) /api/vcs/github/artifactory/api/vcs/tags/github-remote/twbs/bootstrap
```

**Comment by jtamary** [comment]
Yep, I've assumed that the github's remote repository on artifactory is named 'github-remote' (as mine was)
So if you have a remote repository named 'github-remote' you should register the plugin as with your artifactory server url and not the repository path.

`jspm config registries.github.remote <artifactory-server-url>`
 i.e. jspm config registries.github.remote https://yourartifactorycompany.com

Let me know if it helps, and I will update the readme file.

If you wish to register a different name, I will need to change the code accordingly, but it will take me some time.

Many thanks :)

**Comment by jabbera** [comment]
Thanks! That worked.

**Comment by subbiah2806** [comment]
Should it be https://artifacts.company.com or https://artifacts.company.com/api/vcs/downloadBranch/github.com/

**Comment by subbiah2806** [comment]
Tried both dint work for me


err  No version match found for github:xdan/datetimepicker@2.4.3

this is the error i am getting
